version: '3.7'
services:
  postgres:
    image: postgres:11.6-alpine
    environment:
      POSTGRES_USER: miiingle_user
      POSTGRES_PASSWORD: miiingle_password
    ports:
      - 5432:5432
  redis:
    image: redis:5.0.6-alpine
    ports:
      - 6379:6379
    environment:
      REDIS_REPLICATION_MODE: master